[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.10.3"
getopts = "0.2"
protobuf = "3"
zmq = "0.10.0"

[build-dependencies]
protobuf-codegen = "3"
protoc-rust = "^2.0"
